### ISSUE TITLE
Any tips on what's needed to be able to use this within a node script instead of from commandline

### ISSUE THREAD

**Issue by dashmaker** [csabapalfi/freeagent#2]
Hi! I'm trying to put together a simple node.js script that will let me batch upload csv timeslip data into FreeAgent from the command line. While looking into how to do the authorisation, etc. I came across your work. I think I should be able to build off this but not sure where to start. Can you give me any pointers (I'm still a bit of a novice)? Many thanks!

**Comment by csabapalfi** [comment]
Hi, Apologies for not getting back earlier. I somehow managed to configure Github to not notify me about PRs/issues. If this is still relevant please get back to me here and I'm happy to help.

**Comment by csabapalfi** [comment]
I mean if still relevant please reopen.
